# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b19d39b9ee7a3fb2d8338adb026ac6a4a5872cf4f5d6ffbb65ee574b282baf2db0591fde241f6f6a1a8da29c4de2d7254ece5c17be6a63ea3da6d03aa1075bf

test:
  secret_key_base: cf0f51c4fb65ecff596edd2b7b6f27bf14f6cba255b7eb7097be5481a224cf342ed1f03b6967bfdf3669b8ddc2dcfff599e168d06c1e0bea9a22baef251c38c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
